#!/usr/bin/env python3
"""Offline renderer for the pixel-art dashboard, at 360x360.

Mirrors what the firmware will do: the same VLW blob parser as gfx.cpp, the same
8 px Press Start 2P em scaled by integer factors, the same 20 px A8 icon masks
from IconMask.h. Its job is to let the layout be judged on a PC before anything
is flashed.

Every geometry constant below was measured off the ChatGPT mockups rather than
eyeballed. The measurement method matters, so it is recorded here: the day and
night mockups share an identical UI skeleton and differ only in the background
scene, so |day - night| isolates the background and its complement isolates the
chrome. Frames were then located by walking single rows and columns and
recording where a saturated accent hue appears -- far more robust than bounding
boxes, which the background art bleeds into.

Colours are sampled from the mockups and quantised to RGB565, so the preview
shows what the panel will actually show. Text is drawn at integer scales only
(1x = 8 px, 2x = 16, 3x = 24, 4x = 32). Every glyph at those sizes was verified
to be a bit-exact upscale of the 8 px em, so the result is identical to
rasterising natively while costing a single 8 KB font.

    python tools/pixel_preview.py
    python tools/pixel_preview.py --scene night --out C:\\tmp\\preview.png
"""

from __future__ import annotations

import argparse
import os
import re
import struct
import sys
import zlib

# Battery icons live in a sibling module, regenerated by
# tools/make_battery_icons.py alongside main/BatteryIcons.h.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import battery_icon_data  # noqa: E402

WIDTH = 360
HEIGHT = 360

# ---------------------------------------------------------------- palette ---
# Sampled from the mockups (peak-pixel probe) then quantised to RGB565, because
# that is what the ST77916 can display. Values are the post-quantisation ones.


def rgb565(r: int, g: int, b: int) -> tuple:
    """Round-trip a colour through RGB565, as the panel will."""
    value = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return (((value >> 11) & 0x1F) << 3,
            ((value >> 5) & 0x3F) << 2,
            (value & 0x1F) << 3)


VOID = rgb565(2, 8, 18)             # backdrop outside the panel
FILL = rgb565(2, 11, 26)            # panel and button interior
FRAME = rgb565(86, 224, 252)        # panel frame
DIVIDER = rgb565(70, 194, 252)      # rule under the battery row
TEXT = rgb565(255, 255, 255)
DIM = rgb565(108, 148, 185)         # SEND label and the motto
OUTLINE = rgb565(8, 16, 40)         # halo behind the clock and date

STATUS = {
    "THINK": rgb565(50, 220, 254),
    "DONE": rgb565(16, 255, 168),
    "INPUT": rgb565(255, 189, 61),
    "EMPTY": rgb565(200, 214, 230),
    "ERROR": rgb565(255, 71, 84),
    "IDLE": rgb565(140, 138, 255),
}
ACCENT_GREEN = rgb565(16, 255, 168)  # the CODEX LIVE line
WARNING = rgb565(255, 189, 61)       # the setup prompt heading

# ----------------------------------------------------------------- layout ---
# All measured. See outputs/probe_lines.py and outputs/probe_final.py.
CLOCK = dict(cx=180, cy=56, scale=4)
DATE = dict(cx=180, cy=82, scale=1)
PANEL = dict(x=121, y=95, w=118, h=111, cut=4)
DIVIDER_Y = 122
DIVIDER_X0, DIVIDER_X1 = 124, 235
BATTERY = dict(cy=110, gap=8, icon_w=battery_icon_data.ICON_W,
               icon_h=battery_icon_data.ICON_H)
STATUS_LINE = dict(cy=133, scale=1)
QUOTA = dict(cy=158, scale=4)
SEND = dict(cy=182, scale=1)
COUNTDOWN = dict(cy=194, scale=1)
BTN_W, BTN_H = 77, 35
BTN_COLS = (98, 180, 262)
BTN_ROWS = (240, 281)
BTN_CUT = 3
BTN_ICON_DX = 19          # icon centre, relative to the button's left edge
BTN_TEXT_DX = 47          # text column centre, relative to the left edge
BTN_TAG_DY = -2           # tag (A1..A6) sits just below the top frame
BTN_LABEL_DY = 10         # status label below the tag, kept clear
MOTTO = (316, 326)
ICON_SIZE = 20

SCENES = {
    "night": dict(clock="10:08", date="SEP 22 MON", battery=86,
                  status="CODEX LIVE", quota="67%", send="SEND",
                  countdown="4D 17H", bg="bg-night.png",
                  agents=[("THINK", "A1"), ("DONE", "A2"), ("INPUT", "A3"),
                          ("EMPTY", "A4"), ("ERROR", "A5"), ("IDLE", "A6")]),
    "day": dict(clock="10:08", date="SEP 22 MON", battery=86,
                status="CODEX LIVE", quota="67%", send="SEND",
                countdown="4D 17H", bg="bg-day.png",
                agents=[("THINK", "A1"), ("DONE", "A2"), ("INPUT", "A3"),
                        ("EMPTY", "A4"), ("ERROR", "A5"), ("IDLE", "A6")]),
    # The state a freshly flashed board is in: no credentials, so the clock is
    # unknown, every agent is unassigned, and the panel carries the setup
    # prompt instead of the quota readout. Worth being able to see, because it
    # is the first thing anyone meets and it is the only screen where the
    # panel's four rows say something other than link health and quota.
    "setup": dict(clock="--:--", date="-- --- ---", battery=86,
                  setup=True, setup_ssid="CODEX-1A2B",
                  bg="bg-day.png",
                  agents=[("EMPTY", "A1"), ("EMPTY", "A2"), ("EMPTY", "A3"),
                          ("EMPTY", "A4"), ("EMPTY", "A5"), ("EMPTY", "A6")]),
    # The board is on external power: the green bolt remains visible even when
    # charge current has tapered to zero (47% is level 3).
    "charging": dict(clock="10:08", date="SEP 22 MON", battery=47,
                     external_power=True,
                     status="CODEX LIVE", quota="67%", send="SEND",
                     countdown="4D 17H", bg="bg-day.png",
                     agents=[("THINK", "A1"), ("DONE", "A2"), ("INPUT", "A3"),
                             ("EMPTY", "A4"), ("ERROR", "A5"), ("IDLE", "A6")]),
    # Low-battery alarm: 12% drops to level 1, the empty-outline texture.
    "low": dict(clock="10:08", date="SEP 22 MON", battery=12,
                status="CODEX LIVE", quota="67%", send="SEND",
                countdown="4D 17H", bg="bg-day.png",
                agents=[("THINK", "A1"), ("DONE", "A2"), ("INPUT", "A3"),
                        ("EMPTY", "A4"), ("ERROR", "A5"), ("IDLE", "A6")]),
}

# ------------------------------------------------------- time and theme ---
# The clock comes from NTP over WiFi, so every time comparison in the UI is in
# LOCAL time. The board has no RTC: until the first sync the clock is unknown,
# and the theme rule must not be evaluated at all (see theme_for).
TZ_OFFSET_HOURS = 8        # UTC+8, no DST

# Two thresholds, not one. A single "switch at 19:00" leaves the other half of
# the cycle undefined -- nothing would ever switch back to day.
NIGHT_START_HOUR = 19      # >= 19:00 -> night
DAY_START_HOUR = 6         # >= 06:00 -> day

MONTHS = ("JAN", "FEB", "MAR", "APR", "MAY", "JUN",
          "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")
WEEKDAYS = ("MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN")


def theme_for(hour, minute=0):
    """'night' or 'day' for a local wall-clock time."""
    if hour >= NIGHT_START_HOUR or hour < DAY_START_HOUR:
        return "night"
    return "day"


def format_clock(dt):
    """24 h, zero padded -- the design shows '10:08'."""
    return f"{dt.hour:02d}:{dt.minute:02d}"


def format_date(dt):
    """'SEP 22 MON' -- the design's layout."""
    return f"{MONTHS[dt.month - 1]} {dt.day:02d} {WEEKDAYS[dt.weekday()]}"


# ------------------------------------------------------------------- font ---

class Font:
    """Parsed view over a VLW blob, mirroring gfx.cpp's Font::load."""

    def __init__(self, blob: bytes):
        self.data = blob
        (self.count, self.version, self.size, _flags,
         self.ascent, self.descent) = struct.unpack(">6i", blob[:24])
        self.base = 24 + self.count * 28
        self.glyphs = {}
        offset = 0
        for i in range(self.count):
            record = blob[24 + i * 28: 24 + (i + 1) * 28]
            code, height, width, advance, top, left, _ = struct.unpack(">7i", record)
            self.glyphs[code] = (offset, width, height, advance, top, left)
            offset += width * height

    def width(self, text: str) -> int:
        return sum(self.glyphs.get(ord(c), (0, 0, 0, self.size, 0, 0))[3]
                   for c in text)

    def bitmap(self, char: str):
        entry = self.glyphs.get(ord(char))
        if entry is None:
            return None
        offset, width, height, _adv, top, left = entry
        if width == 0 or height == 0:
            return None
        start = self.base + offset
        return self.data[start:start + width * height], width, height, top, left


def load_font(root: str, name: str) -> Font:
    source = open(os.path.join(root, "main", "PixelFonts.h"),
                  encoding="utf-8").read()
    match = re.search(r"static constexpr std::uint8_t " + name
                      + r"\[\] = \{(.*?)\};", source, re.S)
    if not match:
        raise SystemExit(f"{name} not found in PixelFonts.h")
    blob = bytes(int(x, 16)
                 for x in re.findall(r"0x([0-9A-Fa-f]{2})", match.group(1)))
    return Font(blob)


ICON_NAMES = ("kIconThink", "kIconDone", "kIconInput",
              "kIconEmpty", "kIconError", "kIconIdle")


def load_icons(root: str) -> dict:
    source = open(os.path.join(root, "main", "IconMask.h"),
                  encoding="utf-8").read()
    icons = {}
    for name in ICON_NAMES:
        match = re.search(r"static constexpr std::uint8_t " + name
                          + r"\[\] = \{(.*?)\};", source, re.S)
        if not match:
            raise SystemExit(f"{name} not found in IconMask.h")
        blob = bytes(int(x, 16)
                     for x in re.findall(r"0x([0-9A-Fa-f]{2})", match.group(1)))
        assert len(blob) == ICON_SIZE * ICON_SIZE, (name, len(blob))
        icons[name.replace("kIcon", "").upper()] = blob
    return icons


def load_textures(root: str, filename: str = "IconTextures.h") -> dict:
    """Parse IconTextures.h into premultiplied (RGB565 words, A8 coverage)."""
    source = open(os.path.join(root, "main", filename),
                  encoding="utf-8").read()
    textures = {}
    for name in ICON_NAMES:
        mw = re.search(r"static constexpr std::uint16_t " + name
                       + r"_rgb\[\] = \{(.*?)\};", source, re.S)
        ma = re.search(r"static constexpr std::uint8_t " + name
                       + r"_a\[\] = \{(.*?)\};", source, re.S)
        if not mw or not ma:
            raise SystemExit(f"{name} not found in IconTextures.h")
        words = [int(x, 16)
                 for x in re.findall(r"0x([0-9A-Fa-f]{4})", mw.group(1))]
        alphas = bytes(int(x, 16)
                       for x in re.findall(r"0x([0-9A-Fa-f]{2})", ma.group(1)))
        assert len(words) == ICON_SIZE * ICON_SIZE, (name, len(words))
        assert len(alphas) == ICON_SIZE * ICON_SIZE, (name, len(alphas))
        textures[name.replace("kIcon", "").upper()] = (words, alphas)
    return textures


# ----------------------------------------------------------------- canvas ---

class Canvas:
    def __init__(self, background=None):
        if background is None:
            self.px = bytearray(VOID * (WIDTH * HEIGHT))
        else:
            self.px = bytearray(background)

    def blend(self, x, y, colour, coverage=1.0):
        if x < 0 or y < 0 or x >= WIDTH or y >= HEIGHT or coverage <= 0:
            return
        i = (y * WIDTH + x) * 3
        if coverage >= 1.0:
            self.px[i:i + 3] = bytes(colour)
            return
        for c in range(3):
            self.px[i + c] = int(self.px[i + c]
                                 + (colour[c] - self.px[i + c]) * coverage + 0.5)

    def rect(self, x, y, w, h, colour):
        for py in range(y, y + h):
            for px_ in range(x, x + w):
                self.blend(px_, py, colour)

    def pixel_rect(self, x, y, w, h, colour, cut=3, step=2):
        """Rectangle with a stepped (chamfered) corner -- the mockup's shape.

        `cut` is the number of steps and `step` is the horizontal inset each
        one adds, so the first row is inset by cut * step and the level shrinks
        by `step` per row until it reaches zero.

        An earlier comment here claimed the mockup reads "6, 6, 4, 4, 2, 2, 0",
        i.e. two rows per level. That is not what this code does and not what
        the mockup shows. Re-measured off the raw 1254 px art
        (outputs/probe_chamfer.py): the A2 button's chamfer spans 3 levels and
        the panel's spans 4, each roughly one row tall, with total insets of
        about 5 and 9. Those totals match cut=3 and cut=4 at step=2, which is
        exactly what this computes -- so the code stood and the comment was
        wrong. Do not "fix" this to `d // step`; that doubles the chamfer's
        height and no longer matches the art.
        """
        for row in range(h):
            d = min(row, h - 1 - row)
            inset = step * (cut - min(d, cut)) if d < cut else 0
            self.rect(x + inset, y + row, w - 2 * inset, 1, colour)

    def pixel_frame(self, x, y, w, h, colour, fill, cut=3, thickness=1,
                    step=2):
        self.pixel_rect(x, y, w, h, colour, cut, step)
        self.pixel_rect(x + thickness, y + thickness,
                        w - 2 * thickness, h - 2 * thickness, fill,
                        max(0, cut - thickness), step)

    def mask(self, blob, cx, cy, colour, alpha=1.0):
        """An A8 mask, tinted and blended, centred on (cx, cy)."""
        if alpha <= 0:
            return
        x0, y0 = cx - ICON_SIZE // 2, cy - ICON_SIZE // 2
        for row in range(ICON_SIZE):
            for col in range(ICON_SIZE):
                a = blob[row * ICON_SIZE + col] / 255.0 * alpha
                if a > 0:
                    self.blend(x0 + col, y0 + row, colour, a)

    def texture(self, words, alphas, cx, cy, alpha=1.0):
        """A premultiplied RGB565+A8 texture, centred on (cx, cy).

        The artist's icons carry internal shading, so they ship as colour
        textures rather than a coverage mask plus a tint. Premultiplied
        compositing is `out = src + dst * (255 - a) / 255`, which is also what
        makes the brain's fold lines show the button background through, as the
        design does.
        """
        if alpha <= 0:
            return
        x0, y0 = cx - ICON_SIZE // 2, cy - ICON_SIZE // 2
        for row in range(ICON_SIZE):
            for col in range(ICON_SIZE):
                i = row * ICON_SIZE + col
                a = alphas[i] / 255.0 * alpha
                if a <= 0:
                    continue
                value = words[i]
                src = (((value >> 11) & 0x1F) << 3,
                       ((value >> 5) & 0x3F) << 2,
                       (value & 0x1F) << 3)
                x, y = x0 + col, y0 + row
                if x < 0 or y < 0 or x >= WIDTH or y >= HEIGHT:
                    continue
                j = (y * WIDTH + x) * 3
                if a >= 1.0:
                    self.px[j:j + 3] = bytes(src)
                    continue
                inv = 1.0 - a
                for c in range(3):
                    self.px[j + c] = min(255, int(src[c] + self.px[j + c] * inv
                                                  + 0.5))

    def texture_at(self, words, alphas, x0, y0, w, h, alpha=1.0):
        """Same as texture(), but anchored by the top-left corner.

        The status icons are 20x20 squares and want a centre point; the
        battery is a 22x12 rectangle and wants its left edge, so this method
        exists to keep both call sites readable.
        """
        if alpha <= 0:
            return
        for row in range(h):
            for col in range(w):
                i = row * w + col
                a = alphas[i] / 255.0 * alpha
                if a <= 0:
                    continue
                value = words[i]
                src = (((value >> 11) & 0x1F) << 3,
                       ((value >> 5) & 0x3F) << 2,
                       (value & 0x1F) << 3)
                x, y = x0 + col, y0 + row
                if x < 0 or y < 0 or x >= WIDTH or y >= HEIGHT:
                    continue
                j = (y * WIDTH + x) * 3
                if a >= 1.0:
                    self.px[j:j + 3] = bytes(src)
                    continue
                inv = 1.0 - a
                for c in range(3):
                    self.px[j + c] = min(255, int(src[c] + self.px[j + c] * inv
                                                  + 0.5))

    def glyph_pixels(self, font, string, x, y, scale, centre=False):
        """Every lit pixel of `string`, as an (x, y) stream."""
        baseline = y + (font.ascent - font.descent) // 2 * scale
        pen = x - (font.width(string) * scale) // 2 if centre else x
        for ch in string:
            glyph = font.bitmap(ch)
            if glyph is None:
                pen += font.glyphs.get(
                    ord(ch), (0, 0, 0, font.size, 0, 0))[3] * scale
                continue
            bitmap, gw, gh, top, left = glyph
            gx, gy = pen + left * scale, baseline - top * scale
            for row in range(gh * scale):
                source_row = row // scale
                for col in range(gw * scale):
                    if bitmap[source_row * gw + col // scale]:
                        yield gx + col, gy + row
            pen += font.glyphs[ord(ch)][3] * scale

    def text_outlined(self, font, string, x, y, scale, colour, outline,
                      thickness=1, centre=False):
        """Text with a dark halo.

        Required, not decorative: the clock and date sit directly on the scene,
        and in the day theme that scene is a bright sky, so white text without a
        halo is unreadable. The mockups draw the same halo.
        """
        points = list(self.glyph_pixels(font, string, x, y, scale, centre))
        offsets = [(dx, dy)
                   for dy in range(-thickness, thickness + 1)
                   for dx in range(-thickness, thickness + 1)
                   if dx or dy]
        for dx, dy in offsets:
            for px_, py_ in points:
                self.blend(px_ + dx, py_ + dy, outline)
        for px_, py_ in points:
            self.blend(px_, py_, colour)

    def text(self, font, string, x, y, scale, colour, centre=False):
        """Draws `string` at integer `scale`, vertically centred on y."""
        for px_, py_ in self.glyph_pixels(font, string, x, y, scale, centre):
            self.blend(px_, py_, colour)

    def text_width(self, font, string, scale):
        return font.width(string) * scale


# ------------------------------------------------------------------ render ---

def battery_level(percent):
    """Return the firmware's inclusive 0..20 through 81..100 icon band."""
    if percent < 0:
        return 1
    percent = min(100, percent)
    return 1 if percent == 0 else (percent + 19) // 20


def draw_battery(canvas, font, percent, cy, external_power=False):
    """The battery texture chosen by percent + external power, alongside %.

    Mirrors drawBattery() in dashboard_ui.h. Both pull their pixel data from
    battery_icon_data.py so the preview cannot drift from the firmware.
    """
    display_percent = -1 if percent < 0 else min(100, percent)
    label = "--%" if display_percent < 0 else f"{display_percent}%"
    icon_w = BATTERY["icon_w"]
    icon_h = BATTERY["icon_h"]
    gap = BATTERY["gap"]

    # Pick the icon. Level 1 is the lowest visible state; 100% is level 5.
    level = battery_level(display_percent)
    table = battery_icon_data.BATTERY_CHARGING if external_power \
        else battery_icon_data.BATTERY_IDLE
    words, alpha_bytes = table[level - 1]

    tw = canvas.text_width(font, label, 1)
    left = 180 - (icon_w + gap + tw) // 2
    top = cy - icon_h // 2
    canvas.texture_at(words, alpha_bytes, left, top, icon_w, icon_h)

    canvas.text(font, label, left + icon_w + gap, cy, 1, TEXT)


def draw_panel(canvas, font, scene):
    """The information panel -- or the setup prompt, which takes its place.

    Mirrors drawPanel() in dashboard_ui.h. The two branches are exclusive
    rather than layered: link health and quota are both meaningless before the
    device is on a network, so the setup prompt replaces them and reuses the
    same four rows, leaving the layout where it was.
    """
    canvas.pixel_frame(PANEL["x"], PANEL["y"], PANEL["w"], PANEL["h"],
                       FRAME, FILL, cut=PANEL["cut"], thickness=2)

    if scene.get("setup"):
        canvas.text(font, "WIFI SETUP", 180, STATUS_LINE["cy"], 1, WARNING,
                    centre=True)
        canvas.text(font, scene["setup_ssid"], 180, QUOTA["cy"], 1,
                    ACCENT_GREEN, centre=True)
        canvas.text(font, "OPEN BROWSER", 180, SEND["cy"], 1, DIM, centre=True)
        canvas.text(font, "192.168.4.1", 180, COUNTDOWN["cy"], 1, TEXT,
                    centre=True)
        return

    draw_battery(canvas, font, scene["battery"], BATTERY["cy"],
                 external_power=scene.get("external_power", False))
    canvas.rect(DIVIDER_X0, DIVIDER_Y, DIVIDER_X1 - DIVIDER_X0, 1, DIVIDER)

    canvas.text(font, scene["status"], 180, STATUS_LINE["cy"],
                STATUS_LINE["scale"], ACCENT_GREEN, centre=True)
    canvas.text(font, scene["quota"], 180, QUOTA["cy"],
                QUOTA["scale"], TEXT, centre=True)
    canvas.text(font, scene["send"], 180, SEND["cy"],
                SEND["scale"], DIM, centre=True)
    canvas.text(font, scene["countdown"], 180, COUNTDOWN["cy"],
                COUNTDOWN["scale"], TEXT, centre=True)


def render(scene, font, textures, background=None):
    canvas = Canvas(background)

    canvas.text_outlined(font, scene["clock"], CLOCK["cx"], CLOCK["cy"],
                         CLOCK["scale"], TEXT, OUTLINE, thickness=2,
                         centre=True)
    canvas.text_outlined(font, scene["date"], DATE["cx"], DATE["cy"],
                         DATE["scale"], TEXT, OUTLINE, thickness=1,
                         centre=True)

    draw_panel(canvas, font, scene)

    for index, (state, tag) in enumerate(scene["agents"]):
        cx = BTN_COLS[index % 3]
        cy = BTN_ROWS[index // 3]
        colour = STATUS[state]
        x, y = cx - BTN_W // 2, cy - BTN_H // 2
        canvas.pixel_frame(x, y, BTN_W, BTN_H, colour, FILL,
                           cut=BTN_CUT, thickness=2)
        words, alphas = textures[state]
        canvas.texture(words, alphas, x + BTN_ICON_DX, cy)
        canvas.text(font, tag, x + BTN_TEXT_DX, cy + BTN_TAG_DY, 2, colour,
                    centre=True)
        canvas.text(font, state, x + BTN_TEXT_DX, cy + BTN_LABEL_DY, 1, colour,
                    centre=True)

    # The motto sits on open scene, not on a panel, so it needs the same halo as
    # the clock: over the day theme's grass a bare dim grey is unreadable.
    canvas.text_outlined(font, "GOOD IDEAS", 180, MOTTO[0], 1, DIM, OUTLINE,
                         thickness=1, centre=True)
    canvas.text_outlined(font, "TAKE TIME", 180, MOTTO[1], 1, DIM, OUTLINE,
                         thickness=1, centre=True)
    return canvas


def apply_round_mask(canvas):
    """Blank everything outside the visible circle, as the round panel does."""
    r = WIDTH / 2.0
    for y in range(HEIGHT):
        dy = y + 0.5 - r
        for x in range(WIDTH):
            dx = x + 0.5 - r
            if dx * dx + dy * dy > r * r:
                i = (y * WIDTH + x) * 3
                canvas.px[i:i + 3] = bytes((0, 0, 0))


def load_background(path: str):
    """Load a 360x360 background PNG as raw RGB, or None if absent."""
    if not path or not os.path.exists(path):
        return None
    with open(path, "rb") as handle:
        data = handle.read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"{path}: not a PNG")
    pos, idat, width, height, depth, ctype = 8, b"", 0, 0, 0, 0
    while pos < len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        tag = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + length]
        if tag == b"IHDR":
            width, height, depth, ctype = struct.unpack(">IIBB", body[:10])
        elif tag == b"IDAT":
            idat += body
        elif tag == b"IEND":
            break
        pos += 12 + length
    if (width, height) != (WIDTH, HEIGHT) or depth != 8 or ctype != 2:
        raise SystemExit(f"{path}: need 8-bit RGB {WIDTH}x{HEIGHT}, "
                         f"got {width}x{height} depth {depth} type {ctype}")
    raw = zlib.decompress(idat)
    out = bytearray(WIDTH * HEIGHT * 3)
    stride = WIDTH * 3
    prev = bytearray(stride)
    for y in range(HEIGHT):
        start = y * (stride + 1)
        filter_type = raw[start]
        line = bytearray(raw[start + 1:start + 1 + stride])
        for i in range(stride):
            a = line[i - 3] if i >= 3 else 0
            b = prev[i]
            c = prev[i - 3] if i >= 3 else 0
            if filter_type == 1:
                line[i] = (line[i] + a) & 0xFF
            elif filter_type == 2:
                line[i] = (line[i] + b) & 0xFF
            elif filter_type == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif filter_type == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pred) & 0xFF
        out[y * stride:(y + 1) * stride] = line
        prev = line
    return out


def write_png(path: str, canvas: Canvas):
    raw = bytearray()
    for y in range(HEIGHT):
        raw.append(0)
        raw += canvas.px[y * WIDTH * 3:(y + 1) * WIDTH * 3]

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", WIDTH, HEIGHT, 8, 2, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(bytes(raw), 9))
           + chunk(b"IEND", b""))
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(png)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser.add_argument("--scene", default="all", choices=["all", *SCENES])
    parser.add_argument("--at", default=None, metavar="HH:MM",
                        help="local wall-clock time; picks the theme by rule "
                             "and fills the clock/date fields")
    parser.add_argument("--rule", action="store_true",
                        help="print the theme rule's boundaries and exit")
    parser.add_argument("--out", default=None)
    parser.add_argument("--no-round-mask", action="store_true")
    args = parser.parse_args()

    if args.rule:
        print(f"local time = UTC+{TZ_OFFSET_HOURS} (no DST)")
        print(f"night  >= {NIGHT_START_HOUR:02d}:00")
        print(f"day    >= {DAY_START_HOUR:02d}:00")
        print()
        for hour in range(24):
            print(f"  {hour:02d}:00  {theme_for(hour)}")
        return 0

    font = load_font(root, "kPixel8Vlw")
    textures = load_textures(root)
    print(f"font: {font.count} glyphs, {font.size} px em, "
          f"ascent {font.ascent} descent {font.descent}")
    print(f"icons: {', '.join(sorted(textures))} "
          f"({ICON_SIZE}x{ICON_SIZE} RGB565+A8)")

    if args.at:
        hour, _, minute = args.at.partition(":")
        hour, minute = int(hour), int(minute or 0)
        theme = theme_for(hour, minute)
        import datetime
        now = datetime.datetime(2026, 9, 23, hour, minute)
        print(f"at {args.at} local -> {theme} theme, "
              f"clock {format_clock(now)}, date {format_date(now)}")
        scenes = {theme: dict(SCENES[theme],
                              clock=format_clock(now),
                              date=format_date(now))}
    else:
        scenes = SCENES if args.scene == "all" \
            else {args.scene: SCENES[args.scene]}
    out_dir = args.out or os.path.join(root, "tools", "preview")
    for name, scene in scenes.items():
        bg_path = os.path.join(root, "tools", "preview", scene["bg"])
        background = load_background(bg_path)
        print(f"background: {'loaded ' + scene['bg'] if background else 'none (flat void)'}")
        canvas = render(scene, font, textures, background)
        if not args.no_round_mask:
            apply_round_mask(canvas)
        path = args.out if (args.out and len(scenes) == 1) \
            else os.path.join(out_dir, f"pixel-{name}.png")
        write_png(path, canvas)
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
