#!/usr/bin/env python3
"""Generate pixel-art VLW fonts from Press Start 2P and emit a C++ header.

The dashboard is a pixel-art design, so text must land on hard pixel edges. A
TrueType pixel font only stays crisp at integer multiples of its native em
grid, which for Press Start 2P is 8 px. Measured binary-coverage ratios:

    size  8 / 16 / 24 / 32 / 40 / 48  -> 100.0 % pure 0-or-255 alpha
    size 10 / 12 / 20 / 28            -> 45-83 %, i.e. soft anti-aliased edges

So this script refuses any size that is not a multiple of 8, and binarises the
rasterised glyphs at a 128 threshold as a belt-and-braces guarantee.

Only the native 8 px em is emitted. Every glyph at 16/24/32 px was verified to
be a bit-exact integer upscale of its 8 px counterpart -- bitmap, advance and
top extent all included, across all 38 printable glyphs used here -- so the
larger sizes are produced at draw time by nearest-neighbour scaling and cost no
flash. Storing all four sizes would take 176 KB; the 8 px em alone is 8 KB.

The VLW layout matches the Processing/TFT_eSPI format consumed by
main/gfx.cpp: a 24-byte header of big-endian int32s (glyph count, version,
size, flags, ascent, descent), then one 28-byte record per glyph, then the
glyph bitmaps concatenated as one byte of alpha per pixel.

    python scripts/assets/make_pixel_font.py                     # write main/PixelFonts.h
    python scripts/assets/make_pixel_font.py --check             # fail if out of date (CI)
    python scripts/assets/make_pixel_font.py --sizes 16,32       # subset
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

PRINTABLE_ASCII = range(0x21, 0x7F)
NATIVE_GRID = 8
DEFAULT_SIZES = (8,)
BINARY_THRESHOLD = 128

# Name prefix per size, so the header reads naturally at the call site.
SIZE_NAMES = {8: "kPixel8", 16: "kPixel16", 24: "kPixel24", 32: "kPixel32",
              40: "kPixel40", 48: "kPixel48"}


def binarise(image: Image.Image) -> Image.Image:
    """Force every pixel to 0 or 255 so no anti-aliased edge survives."""
    return image.point(lambda value: 255 if value >= BINARY_THRESHOLD else 0)


def generate_vlw(font_path: Path, size: int) -> tuple[bytes, dict]:
    if size % NATIVE_GRID != 0:
        raise ValueError(
            f"size {size} is not a multiple of {NATIVE_GRID}; the glyphs would "
            "be anti-aliased and the pixel-art look would be lost"
        )

    font = ImageFont.truetype(str(font_path), size=size)
    ascent, descent = font.getmetrics()
    headers: list[bytes] = []
    bitmaps: list[bytes] = []
    stats = {"soft": 0, "ink": 0}

    for codepoint in PRINTABLE_ASCII:
        character = chr(codepoint)
        # anchor="ls" puts the origin at the left edge of the glyph on the
        # baseline, which is exactly the coordinate frame gfx.cpp expects.
        left, top, right, bottom = font.getbbox(character, anchor="ls")
        width = max(0, right - left)
        height = max(0, bottom - top)
        advance = max(1, round(font.getlength(character)))
        top_extent = -top

        if width and height:
            bitmap = Image.new("L", (width, height), 0)
            ImageDraw.Draw(bitmap).text((-left, -top), character, font=font,
                                        fill=255, anchor="ls")
            bitmap = binarise(bitmap)
            payload = bitmap.tobytes()
            stats["soft"] += sum(1 for v in payload if 0 < v < 255)
            stats["ink"] += sum(1 for v in payload if v == 255)
        else:
            payload = b""

        headers.append(struct.pack(">7i", codepoint, height, width, advance,
                                   top_extent, left, 0))
        bitmaps.append(payload)

    header = struct.pack(">6i", len(headers), 11, size, 0, ascent, descent)
    return header + b"".join(headers) + b"".join(bitmaps), stats


def array_text(name: str, payload: bytes) -> str:
    rows = []
    for offset in range(0, len(payload), 16):
        chunk = payload[offset:offset + 16]
        rows.append("  " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return (f"static constexpr std::uint8_t {name}[] = {{\n"
            + "\n".join(rows) + "\n};\n")


def build(font_path: Path, sizes) -> str:
    parts = [
        "// Generated by scripts/assets/make_pixel_font.py. Do not edit manually.\n"
        "//\n"
        "// Press Start 2P (SIL Open Font License 1.1). Rasterised only at\n"
        "// multiples of its 8 px native grid and thresholded to hard edges, so\n"
        "// every glyph pixel is either fully on or fully off.\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace dashboard {\nnamespace font_data {\n\n"
    ]
    for size in sizes:
        payload, stats = generate_vlw(font_path, size)
        name = SIZE_NAMES.get(size, f"kPixel{size}")
        parts.append(f"// {size} px em, {size} px advance, "
                     f"{len(payload)} bytes, soft pixels: {stats['soft']}\n")
        parts.append(array_text(f"{name}Vlw", payload))
        parts.append("\n")
    parts.append("}  // namespace font_data\n}  // namespace dashboard\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    root = Path(__file__).resolve().parents[2]
    parser.add_argument("--font", type=Path,
                        default=root / "scripts" / "assets" / "fonts" / "PressStart2P-Regular.ttf")
    parser.add_argument("--output", type=Path,
                        default=root / "main" / "PixelFonts.h")
    parser.add_argument("--sizes", default=",".join(str(s) for s in DEFAULT_SIZES),
                        help="comma-separated em sizes, each a multiple of 8")
    parser.add_argument("--check", action="store_true",
                        help="regenerate and compare; non-zero exit if different")
    args = parser.parse_args()

    sizes = [int(s) for s in args.sizes.split(",") if s.strip()]
    if not args.font.exists():
        print(f"font not found: {args.font}", file=sys.stderr)
        return 1

    try:
        text = build(args.font, sizes)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not args.output.exists():
            print(f"missing {args.output}", file=sys.stderr)
            return 1
        if args.output.read_text(encoding="utf-8") != text:
            print(f"{args.output} is out of date; rerun without --check",
                  file=sys.stderr)
            return 1
        print(f"{args.output} up to date ({len(text)} bytes)")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output}")
    for size in sizes:
        payload, stats = generate_vlw(args.font, size)
        print(f"  {size:2d} px: {len(payload):6d} bytes, "
              f"soft pixels {stats['soft']} (must be 0), ink {stats['ink']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
